# This workflow will build a middlemen project with bundle

name: Build and Publish 20.1.0

on:
  push:
    branches:
      - release-20.1.0

env:
  GOCD_VERSION: '20.1.0'
  RUN_EXTERNAL_CHECKS: true

jobs:
  complete_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.3.0'
      - name: Run the build
        run: |
          bundle install
          bundle exec rake build
  push_to_gh_pages:
    needs: complete_build
    runs-on: ubuntu-latest
    env:
      GITHUB_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Publish to gh pages
        run: |
          git remote add upstream 'https://\${GITHUB_ACTOR}:\${GITHUB_PASSWORD}@github.com/gocd/developer.go.cd'
          bundle install
          bundle exec rake publish --trace
        env:
          REMOTE_NAME: "origin" # might need to update to upstream
          ALLOW_DIRTY: true
  sync_to_s3:
    needs: push_to_gh_pages
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: "${{ secrets.S3_BUCKET }}"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true # would run bundle install
      - name: Upload to S3
        run: bundle exec rake upload_to_s3

